### ISSUE TITLE
NameError: uninitialized constant OEmbed

### ISSUE THREAD

**Issue by tatsuaka** [judofyr/ruby-oembed#49]
I got this error. I tried to change providers.rb to provider.rb but not resolved.
How do I resolve this error?

**Comment by metavida** [comment]
The first thing that comes to mind is perhaps a missing `require`? Could you provide an example of the code that triggers this error for you? 

This is an example of code that I would expect to work:

```ruby
require 'oembed'

my_provider = OEmbed::Provider.new("http://my.cool-service.com/api/oembed_endpoint.{format}")
```

**Comment by tatsuaka** [comment]
Sorry for late reply. I was so newer... Thanks a lot!
