### ISSUE TITLE
No embeddable content error

### ISSUE THREAD

**Issue by tatsuaka** [judofyr/ruby-oembed#50]
I want to use Ted as provider. Here is my code in controller

`ted = OEmbed::Provider.new("http://www.ted.com/talks/oembed.json")`
`ted << "http://ted.com/talks/*"`
`resource = ted.get("http://www.ted.com/talks/dawn_landes_a_song_for_my_hero_the_woman_who_rowed_into_a_hurricane")`

But it returns "No embeddable contet at 〜" 
Whant is wrong?

**Comment by metavida** [comment]
@tatsuaka try this instead

```ruby
ted = OEmbed::Provider.new("http://www.ted.com/talks/oembed.json")
ted << "http://*.ted.com/talks/*"
ted << "https://*.ted.com/talks/*"
resource = ted.get("http://www.ted.com/talks/dawn_landes_a_song_for_my_hero_the_woman_who_rowed_into_a_hurricane")
resource.title #=> "Dawn Landes: A song for my hero, the woman who rowed into a hurricane"
```

The URL pattern that you added to the provider was was set up to match the "ted.com" hostname exactly and didn't match subdomains (like www.ted.com). Switching over support for "*.ted.com" supports all subdomains *and* the subdomain-less "ted.com" hostname. Also, it seems that Ted's oEmbed endpoint does support http**s** URLs so you might as well support those too!

**Comment by tatsuaka** [comment]
It works. Thanks so much for  prompt response.
