### ISSUE TITLE
how do i use embedly with this?

### ISSUE THREAD

**Issue by jm3** [judofyr/ruby-oembed#53]
The ReadMe states that ruby-oembed supports embedly to get a long list of additional providers, but I don't see any documentation on how to do this. Once I've bundled and required the 'embedly' gem, do I need to register somehow with the embedly library?

do I just do OEmbed::Providers.register(OEmbed::Providers::Foo) for the providers I need?

**Comment by metavida** [comment]
You actually don't even need the official embedly gem to get embedly result with the oembed gem. Here's some sample code:

```ruby
# first, add your embedly API key 
# to the included embedly provider. 
OEmbed::Providers::Embedly.endpoint += "?key=#{my_embedly_key}"
# Then you have two options
# Option 1. If you want to get results only from embedly, 
# use that provider directly.
response = OEmbed::Providers::Embedly.get(url)
# Option 2. If you want to use embedly as a fallback 
# in the case that the given URL 
# doesn't match any other provider
# Step 1. Register embedly as a fallback
OEmbed::Providers.register_all
OEmbed::Providers.register_fallback(OEmbed::Providers::Embedly)
# Step 2. Get the resource
resource = OEmbed::Providers.get(url)
```

Let me know how that works out for you!

Disclaimer: I typed this whole answer (including code) in my phone. It is untested & may well contain typos :smiley:
