### ISSUE TITLE
ProviderDiscovery does not work for Facebook and Tumblr

### ISSUE THREAD

**Issue by ghost** [judofyr/ruby-oembed#56]
These providers have discovery links, but ProviderDiscovery can't find them:

https://www.facebook.com/Federer/photos/pb.64760994940.-2207520000.1456668968./10153235368269941/?type=3&theater

http://caesared.tumblr.com/post/140086061155/drugera-gallardo-creepin

**Comment by metavida** [comment]
I've fixed this on the master branch with Pull #57. Hopefully I'll have time to release a new version of the gem soon :smiley:
